### ISSUE TITLE
Confirm data structure and verify data is in a workable format

### ISSUE THREAD

**Issue by AHuffmyer** [AHuffmyer/coral_data_science#1]
I added an initial commit with a coral physiology data set and a README with information about the data sets. 

Our first step is to take a look at these data sets and make sure that the data is in the format we need for analysis. Ariana will rework and change the structure of data as needed.

https://github.com/AHuffmyer/coral_data_science/tree/main/data/coral_physiology 

Add any comments/questions here and I will address any changes needed!

**Comment by dankessler** [comment]
Thanks for getting the ball rolling! I have a few initial clarifying questions

1) Does "colony_id" uniquely identify a colony across host_genus and site? I.e., will `colony_id` of `ACR-258` *always* map to an "Acropora" colony at the "Hilton" site? If so, then `colony_id` + `timepoint` is sufficient to uniquely identify each "observation."

2) Are there really two distinct "data sets," or is it ok for me to think of them as reflecting one big dataset that could be merged? As far as I can tell, most of the colonies/timepoints that are in the first csv also appear in the second csv (there are 15 rows unique to the physiology data set and 8 rows unique to the compositional data set). I can see how the two data sets have rather different "types" of variables, so perhaps that is why they are separated, but I just wanted to understand.

3) Very minor, but the ordering of the "metadata" column is slightly different in the two csv's. One goes `colony_id`, `host_genus`, `timepoint`, `site`, whereas the other goes `colony_id`, `timepoint`, `site`, `host_genus`. Is there a reason for that change in ordering that reflects the way you think about the nesting structure of the data, or is it just an uninteresting happenstance?

4) In the data-specific [`README.md`](https://github.com/AHuffmyer/coral_data_science/tree/main/data/coral_physiology), there's discussion of multiple *fragments* (or "small samples") being taken from each colony at each point in time, but in the data files, the finest level of resolution is at an entire colony. How do the multiple fragments get aggregated down into a single row? Are some fragments used for some measures and other fragments used for others?

**Comment by AHuffmyer** [comment]
1. Yes, you are exactly right. Colony + timepoint = unique observation. 
2. I will upload a revised version of the dataset in which I will add the symbiont relative abundance data into the physiology dataset to generate one csv. They were separated because they were analyzed separately, but its no issue to put them together! This may generate some missing observations, but we can take a look at that once its generated. 
3. The ordering is just happenstance - no reason for the ordering. When I complete merging these datasets we won't have to worry about it. 
4. The finest resolution that we will analyze is at the level of a colony. Replicate tissue samples from the same colony were taken to complete all the analyses, but because these are technical replicates, we will analyze everything at the level of "colony". 

Thank you for taking a look at this! I'll post an update here when the merged data file is available.

**Comment by AHuffmyer** [comment]
I uploaded a merged dataset in the `data` directory. This file now has all available data merged together. Note that some colonies for which we have physiology data we do not have symbiont composition data. We can discuss how we should deal with NAs.

**Comment by dankessler** [comment]
Thanks for updating this. Looking at the code for your merge, it looks like you did a left join (which will include all physio data regardless of whether there is matching symbiont data, but will not include symbiont data that didn't have matching physio data), when I think perhaps we'd rather do a full outer join. 

I've tweaked the code and pushed an updated commit (01ea55e2d893ec6fc88c1ff97143a0e895bce493).

**Comment by AHuffmyer** [comment]
Hi Dan, sounds great. I chose the left_join because we are most interested in how coral physiology changes across site and seasonal gradients and using symbiont communities as a covariate. I think for this first approach using a full_join will be a great initial step and we can further discuss how this affects our analysis.
